name: Release TubeSync

env:
  IMAGE_NAME: tubesync

on:
  release:
    types: [published]

jobs:
  containerise:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.REGISTRY_ACCESS_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        push: true
        tags: ghcr.io/meeb/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
        cache-from: type=registry,ref=ghcr.io/meeb/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
        cache-to: type=inline
        build-args: |
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          RELEASE_TAG=${{ github.event.release.tag_name }}
