name: Release TubeSync

env:
  IMAGE_NAME: tubesync

on:
  release:
    types: [published]

jobs:
  containerise:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Create a new container builder
      run: docker buildx create --name builder && docker buildx use builder
    - name: Build the container image
      run: docker buildx build --platform linux/amd64 --tag $IMAGE_NAME .
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.REGISTRY_ACCESS_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to GitHub Container Registry
      env:
        RELEASE_TAG: ${{ steps.vars.outputs.tag }}
      run: |
        REF_TAG=ghcr.io/meeb/$IMAGE_NAME:$RELEASE_TAG
        docker tag $IMAGE_NAME $REF_TAG
        docker push $REF_TAG
